### ISSUE TITLE
Reimplement autonomous script code for 2016+

### ISSUE THREAD

**Issue by wilstenholme** [frc5687/Outlier1#35]
Fix issues for autoScripts in Robot.java

**Comment by BenBernardCIS** [comment]
I'd like to see:
1. A proper object model for our autonomous elements
2. A tokenizer to convert the character stream to a token stream
3. A parser to convert the token stream to autonomous elements
4. Handling of parallel commands for different subsytems
5. A formal mechanism for subsytems to coordinate
6. Clear support for inputs

**Comment by BenBernardCIS** [comment]
Closing because we've moved this issue to Outlier2.
